server:
  port: 9000

  servlet:
    context-path: /api/v1

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

security:
  jwt:
    token:
      secret-key: 'secretkey'
      uri: '/authenticate'